version: "3.9"

services:
  webapp:
    container_name: vocabularly_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=vocabularly_db;Username=postgres;Password=postgres;
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: .

  db:
    container_name: vocabularly_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vocabularly_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vocabularly_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: