version: "3.9"

services:
  webapp:
    container_name: vocabularly_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    develop:
      watch:
        - action: rebuild
          path: .

  db:
    container_name: vocabularly_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vocabularly_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: